### ISSUE TITLE
About getting numerical information of angle of bounding box.

### ISSUE THREAD

**Issue by yo4hi6o** [hietalajulius/blog#1]
Hi! @hietalajulius
Thank you for sharing your valuable repository. I'm currently studying about rotating bounding boxes. Using this, we were able to display a bounding box rotated with custom data. I would like to get the numerical information "bbox": [cx, cy, bbox_w, bbox_h, angle] of the angle of the bounding box from here.Is it possible?

**Comment by hietalajulius** [comment]
Hi @yo4hi6o ! Yes, the numerical information should be within [this object](https://github.com/hietalajulius/blog/blob/e30b723d3bff2c539b976c312af4525f2a84a341/detectron2/visualize_predictions.py#L45). You can see how it is parsed if you dig deeper into the implementation of detectron's `draw_instance_predictions` there 👍

**Comment by yo4hi6o** [comment]
hi @hietalajulius
from draw_instance_predictions
I was able to get the angle value using draw_rotated_box_with_label from the overlay_instances function.
Thank you
![Screenshot from 2023-01-26 09-29-33](https://user-images.githubusercontent.com/74748434/214727902-6dc005e3-eeb3-4751-a0d5-1640673e0aa7.jpg)
